server:
  port: 8081

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      #      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/leeks
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
#        slave_1:
#          url: jdbc:mysql://127.0.0.1:3306/common_test_two
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
# 天天基金接口
ttjj:
  enable: true
  init: false
  lzjz_init: false
  url:
    # 基金实时信息 http://fundgz.1234567.com.cn/js/001186.js?rt=1463558676006
    last_gsjz: http://fundgz.1234567.com.cn/js/
    # 获取所有基金名称列表代码
    get_funds: http://fund.eastmoney.com/js/fundcode_search.js
    # 基金详细信息：http://fund.eastmoney.com/pingzhongdata/001186.js?v=20160518155842
    fund_info: http://fund.eastmoney.com/pingzhongdata/
    # 历史净值 http://fund.eastmoney.com/f10/F10DataApi.aspx?type=lsjz&code=012414&page=1&sdate=2024-01-10&edate=2024-01-26&per=200
    # &code=012414&sdate=2024-01-10&edate=2024-01-26
    # 重定向 https://fundf10.eastmoney.com/F10DataApi.aspx?type=lsjz&code=012414&sdate=2024-01-25&edate=2024-01-26
    lsjz: http://fund.eastmoney.com/f10/F10DataApi.aspx?type=lsjz&code=
    https_lsjz: https://fundf10.eastmoney.com/F10DataApi.aspx?type=lsjz&code=
# application.yml
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api-docs
